### PR TITLE
custom release to span documents over days/hours/minutes

### PR DESCRIPTION
**Pull request by rschirin**
Hey there, 
I have modified the official `master` branch with a custom release. Basically, I modified the section related to span documents over a window time. Since I had the need to distribute documents in a smaller window time (i.e. only 10 minutes) I implemented this feature. Maybe it could be helpful also to someone else.
The command line follow the example below:

`docker run --rm makelogs --url "https://elastic:xxxx@0.0.0.0:9200"  --indexPrefix "test-" -c 300 --timeWindowType "hour" --timeWindowValue "3/2" --no-reset`

`--timeWindowType` parameter could be `day/hour/minute` (yes, declined to singular)

I haven't any particular JS experience, so I modified the code just to get my purpose avoiding any noticeable error.

### CODE REVIEW

**Comment by gtback** [comment]
cla/check

**Comment by gtback** [comment]
Hi @rschirin . It looks like the commit author is `ruggero.schirinzi@cleafy.com` but you signed the CLA using your Gmail address.

```
❯ git log
commit 5dbbd0fd5694c19794a1ab13363f8d5675ad3485 (HEAD -> rschirin/master)
Author: Roger <ruggero.schirinzi@cleafy.com>
Date:   Mon Nov 7 17:39:08 2022 +0100

    custom release to span documents over days/hours/minutes
```

You can either [amend the commit](url) with the other email address and force push to this branch, or add the Gmail address to your GitHub profile. 

(The CLA checker checks the _author_ of each commit in the PR, not the user who opened the PR, to check they have signed the CLA).

**Comment by gtback** [comment]
@spalger just wanted to make sure you'd seen this.

**Comment by spalger** [comment]
Yeah, I took a look @gtback and while it looks like it would work great I am not in love with the idea of removing the `-d` parameter and instead using `--timeWindowType` and `--timeWindowValue`. I was thinking we might deprecate `-d` and replace it with `-t` with might look something like: `-t 3h/2d`. This isn't how this PR works, and several code changes would be required, so I'm hesitant to ask @rschirin to implement it this way... Sorry, if we can make this a purely additive change and not a breaking change I'd be more than happy to accept the PR.

**Comment by spalger** [comment]
Great! Sounds non-breaking to me! Feel free to update this PR @rschirin, but if you'd like to start a new PR that work too.

**Pull request closed without merging**
